### ISSUE TITLE
Support multiple instances

### ISSUE THREAD

**Issue by S0lll0s** [vrld/SUIT#17]
I would like to allow multiple different parts of my project to draw their respective UI parts, but calling `gui.core.draw` can lead to unexpected results because `update` and `draw` are not always called in the right order or the different parts interfere. Being able to instantiate Quickie would allow each part to seperately keep track of the current UI tree and state.

**Comment by kikito** [comment]
+1 to this.

I would suggest this interface:

``` lua
local suit = require 'suit'
local gui = suit.new()

local input = {text = ""} -- text input data

-- the entire UI is defined inside love.update(dt) (or functions that are called from love.update)
function love.update(dt)
    gui.layout:reset(100,100)

    gui:input(input, suit.layout.row(200,30))
    gui:label("Hello, "..input.text, {align = "left"}, suit.layout.row())

    gui.layout.row() -- padding of one cell
    if gui:button("Close", suit.layout.row()).hit then
        love.event.quit()
    end
end

function love.draw()
    gui:draw()
end

function love.textinput(t)
    gui:textinput(t)
end

function love.keypressed(key)
    gui:keypressed(key)
end
```

You might want to try `gui.Button` instead of `gui:button`. Notice that when instancing you don't need a "core" any more (use `gui` instead of `gui.core`)

**Comment by vrld** [comment]
This was actually planned (layout even already supports instances), but I must have dropped that goal somewhere along the way. It looks like there are dependencies between core, the widgets, and theme that will make this a bit complicated than I'd like (or require an ugly solution), but I'm sure there is a way.

**Comment by vrld** [comment]
I just noticed that this can also be used to implement windows in SUIT: :)

```lua
local suit = require 'suit'

local function draw_window(w, title)
	w.ui:registerDraw(love.graphics.setColor, 128,128,128)
	w.ui:registerDraw(love.graphics.rectangle, 'fill', w.x-1, w.y-1, w.w+2, w.h+2)
	w.ui:registerDraw(love.graphics.setColor, 30,30,30)
	w.ui:registerDraw(love.graphics.rectangle, 'fill', w.x, w.y, w.w, w.h)

	w.ui.layout:reset(w.x,w.y)
	w.active = false
	if w.ui:isActive(w.ui:Button(title, {align='left'}, w.ui.layout:row(w.w, 20)).id) then
		local mx,my = w.ui:getMousePosition()
		local dx,dy = mx - w.mouse_last[1], my - w.mouse_last[2]
		w.x, w.y = w.x + dx, w.y + dy
		w.active = true
	end
	w.mouse_last = {w.ui:getMousePosition()}

	w.ui.layout:reset(w.x+5,w.y+25)

	return w.ui
end

local slider = {value = 0.5}
function love.load()
	windows = {
		{ui = suit.new(), x = 10, y = 10, w = 300, h = 300, mouse_last = {0,0}},
		{ui = suit.new(), x = 320, y = 10, w = 300, h = 400, mouse_last = {0,0}}
	}

	windows[1].update = function(self)
		local ui = draw_window(self, "Window 1")
		ui:Button("Hello, World!", ui.layout:row(200, 30))
		ui:Slider(slider, ui.layout:row(200, 20))
	end

	windows[2].update = function(self)
		local ui = draw_window(self, "Window 2")
		ui:Button("Hello from window 2", ui.layout:row(200, 30))
		ui:Slider(slider, ui.layout:row(200, 20))
	end
end

function love.update()
	local front
	for i, win in ipairs(windows) do
		win:update()
		if win.active then front = i end
	end
	if front then
		table.insert(windows, table.remove(windows, front))
	end
end

function love.draw()
	for _, win in ipairs(windows) do
		win.ui:draw()
	end
end
```

**Comment by qaisjp** [comment]
Nice! Any plans to integrate this into SUIT as an optional component?

**Comment by vrld** [comment]
Nope, windowing support is out of scope. SUITs main goal is to be an easy way to add simple UIs to games, not to develop full blown, UI heavy applications. SUIT should remain small and simple. However, there is no reason why there couldn't be a "widget repository" (a boutique?) or even a fork that implements more widgets, including windows.
