### ISSUE TITLE
input: cursor counts characters, but its bounds are defined in bytes

### ISSUE THREAD

**Issue by pgimeno** [vrld/SUIT#20]
This causes problems like this:
- Enter a bunch of Unicode characters with a codepoint > 127.
- Press the End key.
- Press the Left key.

Expected: cursor should go left one character.
Actual: cursor remains at the end. When pressing Left several times, it eventually will go left (after being pressed as many times as the difference between the length in bytes and in characters).

It seems like the fix is to change len to utf8.len where it's used as bounds for cursor. I haven't tried, though.

**Comment by vrld** [comment]
Should be fixed with SUIT
