### ISSUE TITLE
Problem while trying to run code from example

### ISSUE THREAD

**Issue by debunge** [vrld/SUIT#21]
I've copy&pasted the example from the main page, trying to run and getting the following:

love .
```
Error: Quickie/mouse.lua:67: bad argument #1 to 'isDown' (number expected, got string)
stack traceback:
	[C]: in function 'isDown'
	Quickie/mouse.lua:67: in function 'beginFrame'
	Quickie/core.lua:111: in function 'draw'
	main.lua:127: in function 'draw'
	[string "boot.lua"]:465: in function <[string "boot.lua"]:433>
	[C]: in function 'xpcall'
```
Ubuntu 15.04 with Lua 5.2.3

**Comment by zorfmorf** [comment]
Löve [just yesterday updated from 0.9.2 to 0.10.0](https://love2d.org/forums/viewtopic.php?f=3&t=81447). One of the things changed is the handling of mouse buttons. Quickie needs to be updated first before you can start using it again.

**Comment by zorfmorf** [comment]
Just looked at it, here is a quick fix to get it up and running again. Go to line 66 in mouse.lua and replace

    for _,btn in ipairs{'l', 'm', 'r'} do
         down = down or (love.mouse.isDown(btn) and btn)
    end

with

    for i=1,3 do
        down = down or love.mouse.isDown(i)
    end

The example (and my own project) seem to run fine with just this as far as I can tell.

**Comment by vrld** [comment]
Should be fixed with SUIT
