### ISSUE TITLE
Differences between SUIT and Quickie

### ISSUE THREAD

**Issue by qaisjp** [vrld/SUIT#22]
Are there any major differences?

Also, thanks for the email spam @vrld :3

**Comment by vrld** [comment]
Yes, many: layouting engine, no full-table arguments, separation of control-data and view-data, etc. The documentation will cover these topics (but not the differences to Quickie). It will be there sometime next year ;)

For now, refer to the example in the readme.

**Comment by qaisjp** [comment]
Oh yes, and happy new year :)

**Comment by vrld** [comment]
Closing because the documentation is (almost) complete.
