### ISSUE TITLE
Support for CJK IME text input

### ISSUE THREAD

**Issue by vrld** [vrld/SUIT#26]
In Issue #24, @shakesoda writes:

> CJK IME's need to know where the text box (from the editing cursor to the end of the area, ideally) is on screen in order to position the candidate list appropriately. You need to tell it the region to show up in when it is focused and when the contents change in any way.
> 
> (more info here: https://wiki.libsdl.org/Tutorials/TextInput, if the basics are doable I'm more than willing to do what's needed to get the details right)

Love exposes the TextInput event in [love.textedited(text, start, length)](https://love2d.org/wiki/love.textedited). The candidate text should be displayed at the correct position in the input box, but with a different highlight from the already entered text.

This requires changes in input.lua as well as theme.lua.

**Comment by endlesstravel** [comment]
I'm just try to do it. But there a huge problem on love2d .
Love2d have not ability to post message to IME controls where the ['Candidate List'](https://wiki.libsdl.org/Tutorials/TextInput#CandidateList) will open, if supported.

So what we can do is just show candidata text on input box.
It just like below gif show:
![animation](https://cloud.githubusercontent.com/assets/10757838/20035874/f0ecbd16-a430-11e6-8f64-7e6eea872a2e.gif)

And I pull it https://github.com/vrld/SUIT/pull/49

**Comment by vrld** [comment]
Fixed with PR #49
