### ISSUE TITLE
suit.draw() doesn't setColor for itself

### ISSUE THREAD

**Issue by LudwikJaniuk** [vrld/SUIT#33]
Calling
```
lg.setColor(255, 0 ,0)
suit.draw()
```
Will only draw the red channel for the whole GUI. I'm assuming this is an omission of `lg.setColor(255, 255, 255)` somewhere?

("Why would somebody do that?" If GUI code is called after game rendering code, if is probable that the color has been set do something other than white. The way I see it it's good practice to have every draw call set up the graphics state for itself, instead of assuming that preceding code has cleaned up after itself):

**Comment by vrld** [comment]
Strange; that should only affect the ImageButton widget ([which uses the color set at invocation of ImageButton](https://github.com/vrld/SUIT/blob/master/imagebutton.lua#L31)), the other widgets *do* set color ([see here](https://github.com/vrld/SUIT/blob/master/theme.lua#L21)). I will try to reproduce the bug when I'm back home.

**Comment by LudwikJaniuk** [comment]
I was using ImageButton specifically, so that would be it. If this is the intended behavior, I'd ask only for it to be mentioned in [the docs](https://suit.readthedocs.org/en/latest/widgets.html#ImageButton).
