### ISSUE TITLE
Layout docs example errors

### ISSUE THREAD

**Issue by Wargog** [vrld/SUIT#35]
Using the following code, the layout class yields the error which you can see in the [screenshot of LOVE](https://gyazo.com/10ffac0612657e337ed457de34f8d3ad)
```
suit.Label("Pause Menu", suit.layout.row())
suit.Label("Test", suit.layout.row())
```

**Comment by vrld** [comment]
You need to use `suit.layout:row()`, as described in the [getting started guide](http://suit.readthedocs.org/en/latest/gettingstarted.html#layout).

Leaving this open, because the [layout documentation](http://suit.readthedocs.org/en/latest/layout.html) contains invalid examples.

**Comment by Wargog** [comment]
I figured that out, but I will update the issue to reflect the errors in the documentation
