### ISSUE TITLE
ImageButton ignores clicks if the image was just created

### ISSUE THREAD

**Issue by LudwikJaniuk** [vrld/SUIT#36]
It is smart to create images once and store them for reuse every frame. But if you happen to recreate images every frame, ImageButton will not react to mouse clicks at all (tho it still draws the image correctly).

I use this function to create images:

```
function createImage(w, h, col)
    local data = love.image.newImageData(w, h)
    for x = 0, w-1 do
        for y = 0, h-1 do
            data:setPixel(x, y, _G.unpack(col))
        end
    end
    return love.graphics.newImage(data)
end
```

If I use this function to create an image, save the image in a variable, and then use that variable consecutively for calls to `ImageButton(...)`, it works as expected. But if I call it directly to recreate an image each time I want to call `ImageButton(...)`, then the `.hit` of the returned state is never true, even though I press the button rendered, and the button is rendered correctly.

I know that recreating the button each frame is stupid and slow, but I would still have expected SUIT to do its part correctly.

**Comment by vrld** [comment]
Same cause as in #37: The image is used as button id, but the button id changes every frame. You will have to use the `id` option or [Image:refresh(data)](http://love2d.org/wiki/(Image):refresh) so that the id stays consistent over frames.
