### ISSUE TITLE
Auto enable repeat backspace and other function keys when textbox is on focus

### ISSUE THREAD

**Issue by buckle2000** [vrld/SUIT#40]
backspace, arrow keys and etc. are not considered as text input.
this means that i cannot delete all text by **holding** the backspace key down (which only delete one character).
can you add a way to "repeat" key inputs like `backspace`, arrow keys and such

**Comment by vrld** [comment]
Key repeat should be enabled by the user with [love.keyboard.setKeyRepeat](https://love2d.org/wiki/love.keyboard.setKeyRepeat).
