### ISSUE TITLE
Programmatically interact with widgets

### ISSUE THREAD

**Issue by rosshadden** [vrld/SUIT#41]
I am trying to make it so hitting `K` and `J` will focus buttons (up and down, respectively), and then hitting `Enter` would do the same thing as clicking them.  Or if I knew which button was selected, on `Enter` I could trigger the same action it is bound to myself.

I can't figure out how to do this by reading the docs, so I wanted to ask if it's even possible.

Thanks

**Comment by rosshadden** [comment]
If I could manually set `hovered` or `hit` from within the `keypressed` handler, I would be able to do what I am asking for.  However they are currently read-only properties.

Consider the following example as a demonstration:

```lua
local suit = require 'suit'

local button
local focusedButton

function love.update()
	suit.layout:reset(0, 0)

	button = suit.Button('foo', suit.layout:row())

	if button.hovered then print 'Button was hovered' end

	if button.hit then print 'Button was hit' end
end

function love.draw()
	suit.draw()
end

function love.keypressed(key)
	suit.keypressed(key)

	if key == 'j' then
		focusedButton = button
		focusedButton.hovered = true
	end

	if key == 'enter' and focusedButton ~= nil then
		focusedButton.hit = true
	end
end
```

**Comment by vrld** [comment]
More than half a year late (sorry), but still: commit c0943eae16bc60022860db8767d75bcf3432bed9 adds `setHovered(id)`, `setActive(id)` and `setHit(id)`, which should enable keyboard interaction.

**Comment by xordspar0** [comment]
Hm, I'm having trouble getting those functions to work. Below is a minimal version of what I'm doing. Am I doing something wrong?

```lua
local suit = require('suit')

function love.update()
	suit.Button("Button A", 5,5, 100,20)
	suit.Button("Button B", 5,30, 100,20)

	suit:setHovered("Button A")
end

function love.draw()
  suit:draw()
end
```

**Comment by tcfunk** [comment]
@xordspar0 I think you want `suit.setHovered` and `suit.draw` rather than `suit:setHovered` and `suit:draw`

**Comment by xordspar0** [comment]
Nope, doesn't fix it. Well, we don't have to troubleshoot my code here. I just thought that maybe it was a bug in suit.
