### ISSUE TITLE
Overlapped controls and click order

### ISSUE THREAD

**Issue by linux-man** [vrld/SUIT#51]
```
local suit = require 'suit'

local change = false
local drive = 'change'

function love.load()
end

function love.update()
	suit.layout:reset()
	if suit.Button(drive, suit.layout:row(120, 20)).hit then change = true end
	if suit.Button("test", suit.layout:row(120, 20)).hit then print("click") end
	if change then
		suit.layout:push(0, 20)
		if suit.Button('c:', suit.layout:row(120, 20)).hit then drive = 'c' print('c') change = false end
		if suit.Button('d:', suit.layout:row(120, 20)).hit then drive = 'd' print('d') change = false end
		if suit.Button('e:', suit.layout:row(120, 20)).hit then drive = 'e:' print('e') change = false end
		if suit.Button('f:', suit.layout:row(120, 20)).hit then drive = 'f:\\' print('f') change = false end
		suit.layout:pop()
	end
end

function love.draw()
	suit:draw()
end
```
This example presents 2 issues:
It's the hidden button "test" that respond to the hit event.
Something strange happens when the "change" button label ends with ":".
Since SUIT pretends to be a simple GUI library, I guess it's too much to try to develop this kind of interface (with overlapping elements).

**Comment by vrld** [comment]
Two issues here: two buttons with the same name and hence id and the draw order not being  the same as the update order. See [here](suit.readthedocs.io/en/latest/gettingstarted.html) how to fix the first issue. The second issue will be fixed with commit c0943eae16bc60022860db8767d75bcf3432bed9.
