### ISSUE TITLE
Hold backspace to remove multiple characters, password input and input label

### ISSUE THREAD

**Issue by Whitecl4ws** [vrld/SUIT#52]
If possible, these features could be added to make the library friendlier to login screens

**Comment by Whitecl4ws** [comment]
All features will be pushed to the tree hopefully, i got them implemented

**Comment by vrld** [comment]
Should be done on client side with [love.keyboard.setKeyRepeat(true)](https://love2d.org/wiki/love.keyboard.setKeyRepeat)

**Comment by cdwfs** [comment]
Sorry for the necro-post on an old issue, but just ran into the same issue as the original poster and am curious why `love.keyboard.setKeyRepeat(true)` is the correct answer here. I've added a text input field with `suit.Input(...)`, and without calling `love.keyboard.setKeyRepeat(true)`, if I click in the text field and hold down e.g. the "D" key, then after a while I get a bunch of "D"s in the text field. But no matter how long I hold down the Backspace key, only the last "D" character is deleted. Is this expected, or a bug (in either SUIT or love)?

**Comment by vrld** [comment]
The implementation that is [already there](https://github.com/love2d/love/blob/main/src/modules/event/sdl/Event.cpp#L215) is most probably better than anything I'd come up with. I have no idea why you get repeated keys for letters, but not for backspace.
