### ISSUE TITLE
Scaling not working properly

### ISSUE THREAD

**Issue by Eritar** [vrld/SUIT#55]
I'm coding mobile game, which needs to work at all resolutions. I managed to work this snippet of code: `width, height = love.graphics.getDimensions()`
`coefW = width/1920`
`coefH = height/1080`
`love.graphics.scale(coefW, coefH)`

This scales everything on screen to a coefficent of division of device screen resolution to Full HD resolution (which all game are written in). So, SUIT barely works with this. Images of buttons and buttons itself scales properly, but the "collision box" remains the same size and position as original.

This is the original 1920/1080 resolution:
![native_button](https://cloud.githubusercontent.com/assets/12482353/24333220/93b44070-125c-11e7-9317-0a3118d2e9f8.gif)

That is scaled to 800/600 resolution. Purple rectangle represents original position and size in both gifs:
![button_in_800x600](https://cloud.githubusercontent.com/assets/12482353/24333237/02ade9cc-125d-11e7-97b3-4189ec1b12d9.gif)

**Comment by vrld** [comment]
You have to use [updateMouse()](http://suit.readthedocs.io/en/latest/core.html#updateMouse) to tell SUIT about the camera transformation - see also [here](https://github.com/vrld/SUIT/blob/master/core.lua#L163)
