### ISSUE TITLE
Identical buttons are called at the same time

### ISSUE THREAD

**Issue by SmartSoda** [vrld/SUIT#56]
If you create two buttons, regardless of the position, if the first arguments are the same, both are activated when the one in which was created first is clicked.

**Comment by vrld** [comment]
In these cases you need to use a widget id, see [here](http://suit.readthedocs.io/en/latest/widgets.html#common-options). As of commit 6cb5596437a6bcd26d55717122ec222dd70a9620 there is also a section in the [Gettng started](http://suit.readthedocs.io/en/latest/gettingstarted.html#widget-ids) guide.
