### ISSUE TITLE
LOVE2D 0.11 is here, and here's the simple fix to make it work.

### ISSUE THREAD

**Issue by toomykins** [vrld/suit#63]
using suit but everything looking a little "white" to you? replace the theme.color definitions to a scale of 0 to 1 rather than 0 to 255.
like so

```
theme.color = {
	normal   = {bg = { 0.258823529, 0.258823529, 0.258823529}, fg = {0.737254902,0.737254902,0.737254902}},
	hovered  = {bg = { 0.196078431,0.6,0.733333333}, fg = {1,1,1}},
	active   = {bg = {1,0.6,  0}, fg = {1,1,1}}
}
```

and the thing's fixed.

**Comment by vrld** [comment]
Fixed with 2f3db27769997a8e3f96e64c41967c4feb9150f1
