### ISSUE TITLE
Game controller support

### ISSUE THREAD

**Issue by xordspar0** [vrld/suit#66]
Our game supports mouse+keyboard and game controllers. Is there an easy way to use game controllers with suit? The main thing I'm thinking of would be to scroll through groups of buttons with a stick or d-pad and the press A to choose one. I can think of two options:

1. I wouldn't mind keeping track of the selected button and listening for button presses in my own code, but I can't find a way to highlight buttons as if there's a mouse hovering over them.

2. If it's a good fit for suit, I could submit a patch to add game controller support to suit itself.

**Comment by xordspar0** [comment]
Oh, I just found #41. I really did search through the existing issues, but I missed that. 😅 That's exactly what I had in mind for my option 1.

**Comment by vrld** [comment]
No worries. You can also just simulate keypresses by calling `suit.keypressed(key)` (see [here](https://suit.readthedocs.io/en/latest/core.html)).
