### ISSUE TITLE
ImageButton error on LÖVE 11.1

### ISSUE THREAD

**Issue by deagahelio** [vrld/suit#68]
When trying to create an ImageButton widget, this error shows up:

```
Error: libs/suit/imagebutton.lua:14: attempt to call method 'getData' (a nil value)
stack traceback:
        [string "boot.lua"]:637: in function 'getData'
        libs/suit/imagebutton.lua:14: in function 'hit'
        libs/suit/core.lua:103: in function 'registerMouseHit'
        libs/suit/imagebutton.lua:13: in function 'ImageButton'
        main.lua:51: in function 'update'
        [string "boot.lua"]:509: in function <[string "boot.lua"]:493>
        [C]: in function 'xpcall'
```

I believe this has something to do with [(Image):getData being removed in 11.0](https://love2d.org/wiki/(Image):getData).

**Comment by vrld** [comment]
Unfortunately LÖVE 11.0 dropped that function without replacement. SUIT needs to query pixels to figure out if the button was hit, but there does not seem to be a way to do this right now. I can some worarounds, but none of them seem good. Any suggestions?

**Comment by deagahelio** [comment]
Maybe have the user pass in the ImageData along with the Image itself? It's the only solution I can think of

**Comment by shakesoda** [comment]
It's a bit obtuse, but if you can't reasonably expect a user to pass an ImageData you could render the image to a (throwaway) canvas and use Canvas:newImageData()

**Comment by vrld** [comment]
Finally opted to simply add the alpha test as an option `mask`. This seems to cause the least friction.
