### ISSUE TITLE
Multiple buttons react on hover

### ISSUE THREAD

**Issue by Nedok** [vrld/suit#70]
When having overlapping buttons they both highlight on mouse hover. Just checking if that is intended behavior. It seems strange as only one of the buttons react when pressed.

```lua
local suit = require 'suit'

function love.update(dt)
   if suit.Button("Hello", 100,100,100,100).hit then
      print("Hello")
   end

   if suit.Button("Bye", 150,150,100,100).hit then
      print("Bye")
   end
end

function love.draw()
   suit.draw()
end
```

**Comment by vrld** [comment]
What is the use-case for letting buttons overlap like this?

**Comment by Nedok** [comment]
This was just an example to demonstrate it. However i can think of some scenarios.
Having a "floting" message box over existing elements. Buttons that passes over one another as part of animations. Having an user movable map with buttons, together with buttons for controlling zoom... just to name a few.

**Comment by vrld** [comment]
Cases that can be conceptionally separated into multiple UIs (floating windows, button-overlay, etc.) can/should be handled with separate suit instances (see comment chain of #17 for an example of floating windows). It's a simple fix though :)
